--
-- PostgreSQL database dump
--

-- Dumped from database version 13.2
-- Dumped by pg_dump version 13.2

-- Started on 2021-05-18 16:59:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 204 (class 1259 OID 16904)
-- Name: employees; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employees (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL
);


ALTER TABLE public.employees OWNER TO postgres;

--
-- TOC entry 206 (class 1259 OID 16917)
-- Name: employers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers (
    user_id integer NOT NULL,
    web_site character varying(50) NOT NULL,
    web_site_email character varying(50) NOT NULL,
    phone_number character varying(20) NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);


ALTER TABLE public.employers OWNER TO postgres;

--
-- TOC entry 205 (class 1259 OID 16915)
-- Name: employers_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 208 (class 1259 OID 16930)
-- Name: employers_verification_code_email; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_verification_code_email (
    id integer NOT NULL,
    employer_id integer NOT NULL,
    verification_code_by_email character varying(100) NOT NULL
);


ALTER TABLE public.employers_verification_code_email OWNER TO postgres;

--
-- TOC entry 207 (class 1259 OID 16928)
-- Name: employers_verification_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers_verification_code_email ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_verification_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16978)
-- Name: employers_verification_coded_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_verification_coded_employee (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    is_verified_by_employee boolean DEFAULT false NOT NULL
);


ALTER TABLE public.employers_verification_coded_employee OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16976)
-- Name: employers_verification_coded_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers_verification_coded_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_verification_coded_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16961)
-- Name: employers_verification_employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employers_verification_employee (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    employer_id integer NOT NULL
);


ALTER TABLE public.employers_verification_employee OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16959)
-- Name: employers_verification_employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employers_verification_employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employers_verification_employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 16890)
-- Name: job_seekers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_seekers (
    user_id integer NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    date_of_birth date NOT NULL,
    is_verified boolean DEFAULT false NOT NULL
);


ALTER TABLE public.job_seekers OWNER TO postgres;

--
-- TOC entry 202 (class 1259 OID 16888)
-- Name: job_seekers_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_seekers ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_seekers_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16949)
-- Name: job_seekers_verification_code; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_seekers_verification_code (
    id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    verification_code_by_email character varying(100) NOT NULL
);


ALTER TABLE public.job_seekers_verification_code OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16947)
-- Name: job_seekers_verification_code_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_seekers_verification_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.job_seekers_verification_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16942)
-- Name: job_title; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.job_title (
    id integer NOT NULL,
    job_title character varying(50) NOT NULL,
    description character varying(300) NOT NULL
);


ALTER TABLE public.job_title OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16940)
-- Name: job_title_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.job_title ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.job_title_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 201 (class 1259 OID 16877)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    "Id" integer NOT NULL,
    email character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    is_active boolean DEFAULT false
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 200 (class 1259 OID 16875)
-- Name: users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2909 (class 2606 OID 16909)
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2911 (class 2606 OID 16922)
-- Name: employers employers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT employers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2913 (class 2606 OID 16934)
-- Name: employers_verification_code_email employers_verification_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_code_email
    ADD CONSTRAINT employers_verification_code_pkey PRIMARY KEY (id);


--
-- TOC entry 2921 (class 2606 OID 16983)
-- Name: employers_verification_coded_employee employers_verification_coded_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_coded_employee
    ADD CONSTRAINT employers_verification_coded_employee_pkey PRIMARY KEY (id);


--
-- TOC entry 2919 (class 2606 OID 16965)
-- Name: employers_verification_employee employers_verification_employee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employee
    ADD CONSTRAINT employers_verification_employee_pkey PRIMARY KEY (id);


--
-- TOC entry 2905 (class 2606 OID 16897)
-- Name: job_seekers job_seekers_nationality_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_seekers
    ADD CONSTRAINT job_seekers_nationality_id_key UNIQUE (nationality_id);


--
-- TOC entry 2907 (class 2606 OID 16895)
-- Name: job_seekers job_seekers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_seekers
    ADD CONSTRAINT job_seekers_pkey PRIMARY KEY (user_id);


--
-- TOC entry 2917 (class 2606 OID 16953)
-- Name: job_seekers_verification_code job_seekers_verification_code_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_seekers_verification_code
    ADD CONSTRAINT job_seekers_verification_code_pkey PRIMARY KEY (id);


--
-- TOC entry 2915 (class 2606 OID 16946)
-- Name: job_title job_title_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_title
    ADD CONSTRAINT job_title_pkey PRIMARY KEY (id);


--
-- TOC entry 2901 (class 2606 OID 16887)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 2903 (class 2606 OID 16882)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY ("Id");


--
-- TOC entry 2927 (class 2606 OID 16966)
-- Name: employers_verification_employee fk_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employee
    ADD CONSTRAINT fk_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(user_id);


--
-- TOC entry 2929 (class 2606 OID 16984)
-- Name: employers_verification_coded_employee fk_employee_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_coded_employee
    ADD CONSTRAINT fk_employee_id FOREIGN KEY (employee_id) REFERENCES public.employees(user_id);


--
-- TOC entry 2925 (class 2606 OID 16935)
-- Name: employers_verification_code_email fk_employer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_code_email
    ADD CONSTRAINT fk_employer_id FOREIGN KEY (id) REFERENCES public.employers(user_id);


--
-- TOC entry 2928 (class 2606 OID 16971)
-- Name: employers_verification_employee fk_employer_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers_verification_employee
    ADD CONSTRAINT fk_employer_id FOREIGN KEY (employer_id) REFERENCES public.employers(user_id);


--
-- TOC entry 2926 (class 2606 OID 16954)
-- Name: job_seekers_verification_code fk_job_seeker_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_seekers_verification_code
    ADD CONSTRAINT fk_job_seeker_id FOREIGN KEY (id) REFERENCES public.job_seekers(user_id);


--
-- TOC entry 2923 (class 2606 OID 16910)
-- Name: employees fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users("Id");


--
-- TOC entry 2924 (class 2606 OID 16923)
-- Name: employers fk_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.employers
    ADD CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES public.users("Id");


--
-- TOC entry 2922 (class 2606 OID 16898)
-- Name: job_seekers user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.job_seekers
    ADD CONSTRAINT user_id FOREIGN KEY (user_id) REFERENCES public.users("Id");


-- Completed on 2021-05-18 16:59:48

--
-- PostgreSQL database dump complete
--

